### ISSUE TITLE
Is it possible to write gradle scripts without the buildScript header?

### ISSUE THREAD

**Issue by distributev** [distributev/mailmerger#7]
![image](https://user-images.githubusercontent.com/19224635/39466888-7358ba30-4d2b-11e8-8470-4803a9ebee49.png)

**Comment by p-bye** [comment]
If you want to omit the `buildscript` then the only alternative I can think of is to run the mailmerger-cmdline as an actual command, rather than bringing it in as a dependency.

I've pushed up a branch https://github.com/distributev/mailmerger/tree/alternative

See the build.gradle in the watch2 folder for an example of what I mean.

**Comment by distributev** [comment]
Hello,
I tried to look at watch2 but I still see buildScript at the top. In any case I'm interested to tell me couple of examples for scripts types where buildScript section is mandatory and another set of example scripts where just by watching at the script content nothing related with "build" will be visible. I don't need you to write code only to tell me here when buildScript section is mandatory and when we can code gradle scripts without "build" assumptions.

**Comment by p-bye** [comment]
Sorry, I'd not committed the changes to the branch.  Should be there now.

https://github.com/distributev/mailmerger/blob/alternative/watch2/build.gradle

**Comment by p-bye** [comment]
The `buildscript` section of a Gradle `build.gradle` file defines any dependencies required for Gradle to execute the build.
e.g. in https://github.com/distributev/mailmerger/blob/alternative/watch/build.gradle the `mailmerger-cmdline` dependency is required to use the `MailMerger` class directly in the buildscript.

In https://github.com/distributev/mailmerger/blob/alternative/watch2/build.gradle this dependency is not required as the location of the jar file is specified as a parameter to the build and runs a `java -jar` command via exec.

**Comment by distributev** [comment]
Please merge watch2 into the main branch. This is how I need - the server should only "wrap functionality" while being as independent as possible from the functionality which is being "wrapped" or deployed into the server.

**Comment by p-bye** [comment]
watch2 has been merged into the main branch and become the main watch folder.
